name: My First Workflow

on:
  push:

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository
        uses: actions/checkout@v4
      
      - name: Listing
        run: ls

  list:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: ls


