name: Index File copy

on:
  push:

jobs:
  Copy_Index_File:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v7

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rsync -av --delete ./index.html /var/www/html/

